=== margaretha/standards/SIS/clarin/schemas/domains.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="domains">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="metadomain"/>
        <xs:element maxOccurs="unbounded" ref="domain"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="metadomain">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="desc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="domain">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="desc"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer">
        <xs:annotation>
          <xs:documentation>This is an internal handle, used at some places for easier processing.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="orderBy" use="optional">
        <xs:annotation><xs:documentation>This attribute identifies the metadomain, such as "Annotation" for various specific kinds of annotation.</xs:documentation>
          <xs:appinfo>
            <sch:pattern xmlns:sch="http://purl.oclc.org/dsdl/schematron">
              <sch:rule context="//domain/@orderBy">
                <sch:assert
                  test=". = //domains/metadomain/name"
                  >The value of @orderBy (<sch:value-of select="."/>) must be registered as a metadomain name.</sch:assert>
              </sch:rule>
            </sch:pattern>
          </xs:appinfo>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="desc">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="a">
    <xs:complexType mixed="true">
      <xs:attribute name="href" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== margaretha/standards/SIS/clarin/data/domains.xml
<?xml-model href="../schemas/domains.xsd" type="application/xml" 
            schematypens="http://purl.oclc.org/dsdl/schematron"?>
<domains xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../schemas/domains.xsd">
    
    <metadomain>
        <name>Annotation</name>
        <desc>These domains group together functions of additional pieces of data that are used to classify elements of the source data in various ways.</desc>
    </metadomain>
    <metadomain>
        <name>Data/Resource Description</name>
        <desc>These domains describe functions related to various kinds of descriptions of particular kinds of data and also entire resources. 
            Most of them correspond to various aspects of the unqualified notion of metadata.</desc>
    </metadomain>
    <metadomain>
        <name>Source Language Data</name>
        <desc>These domains group what is often referred to as "primary data" -- electronic, curated and prepared to be annotated and futher processed.</desc>
    </metadomain>
    <metadomain>
        <name>Machine Learning</name>
        <desc>These domains group the functions of data used in the creation, fine-tuning and serving machine learning models, from "classical" 
            through neural networks to large language models.</desc>
    </metadomain>
    
    <!-- manually sync the state of the taxonomy below with the schema for recommendations, i.e. recommendation.xsd -
     unless an automatic method is created, e.g. by parsing this file into a schema fragment by script, and
     making sure that that fragment gets imported by recommendation.xsd... The purpose of such a move would be 
     content-completion and dynamic documentation of content selections (as in the definition of the element "domain"). -->
    
    <domain id="1" orderBy="Source Language Data">
        <name>Audiovisual Source Language Data</name>
        <desc>Audio or video recordings providing spoken/multimodal or signed language data for
            research purposes.</desc>
    </domain>
    <domain id="2" orderBy="Source Language Data">
        <name>Image Source Language Data</name>
        <desc>Digitized images of analogue sources of written language data for research purposes
            (e.g. facsimiles, scans of handwriting, photos of inscriptions).</desc>
    </domain>
    <domain id="3" orderBy="Source Language Data">
        <name>Textual Source Language Data</name>
        <desc>Written unstructured/plain text or originally structured text (e.g. HTML), without linguistic or other mark-up added for research purposes.</desc>
    </domain>
    <domain id="4" orderBy="Data/Resource Description">
        <name>Contextual Data</name>
        <desc>Images (photos or drawings) or documents relevant to the communicative event or text, but not part of the source language data.</desc>
    </domain>
    <domain id="5" orderBy="Annotation">
        <name>Text Annotation</name>
        <desc>Annotations of textual sources/written text, with the original text included or as stand-off.</desc>
    </domain>
    <domain id="6" orderBy="Annotation">
        <name>Audiovisual Annotation</name>
        <desc>Annotations of audiovisual sources, usually including a basic rendering of the spoken content (transcription) and, sometimes, further annotation.</desc>
    </domain>
    <domain id="7" orderBy="Annotation">
        <name>Image Annotation</name>
        <desc>Annotations of image sources.</desc>
    </domain>
    <domain id="8" orderBy="Data/Resource Description">
        <name>Contextual Information</name>
        <desc>Structured information on the communicative event or text and its creators (i.e. participants or authors) relevant for analysis.</desc>
    </domain>
    <domain id="9" orderBy="Data/Resource Description">
        <name>Catalogue Metadata</name>
        <desc>Basic structured information for discoverability and general description, to be openly provided for harvesting.</desc>
    </domain>
    <domain id="10" orderBy="Data/Resource Description">
        <name>Metadata</name>
        <desc>Comprehensive structured information including descriptive, structural and administrative metadata. See the <a href="https://www.niso.org/publications/understanding-metadata-2017">National Information Standards Organization primer on metadata</a> for further hints.</desc>
    </domain>
    <domain id="11" orderBy="Data/Resource Description">
        <name>Documentation</name>
        <desc>Unstructured documentation of the resource and its parts such as corpus or annotation guidelines.</desc>
    </domain>
    <domain id="12">
        <name>Lexical Resource</name>
        <desc>Structured (item-based) resources for lexical and/or conceptual information on units of language (e.g., wordlists, lexicons, WordNets, etc.)</desc>
    </domain>
    <domain id="13">
        <name>Tool Support</name>
        <desc>Tool-related formats required for specific functionality of the tool or reliable reuse of resources (e.g., tagsets, annotation schemes, vocabularies, language models, parameter files, and other specifications or settings).</desc>
    </domain>
    <domain id="14">
        <name>Geodata</name>
        <desc>Information on geographic locations.</desc>
    </domain>
    <domain id="15">
        <name>Statistical Data</name>
        <desc>Data from surveys and tests in numeric formats.</desc>
    </domain>
    <domain id="16" orderBy="Data/Resource Description">
        <name>Language Description</name>
        <desc>Structured or unstructured descriptions of linguistic varieties or phenomena, typological databases, etc.</desc>
    </domain>
    <domain id="17">
        <name>Packaging</name>
        <desc>Packaging formats of various nature (archiving, compression, library) if no more specific domain is suitable.</desc>
    </domain>
    <domain id="18" orderBy="Machine Learning">
        <name>ML Data Preparation</name>
        <desc>Data curated and formatted for integration into machine learning systems. </desc>
    </domain>
    <domain id="19" orderBy="Machine Learning">
        <name>ML Model Training</name>
        <desc>Data used for pre-training and fine-tuning of machine learning models.</desc>
    </domain>
    <domain id="20" orderBy="Machine Learning">
        <name>ML Model Exchange</name>
        <desc>Data that enable the sharing and deployment of machine learning models across different systems and platforms.</desc>
    </domain>
    <domain id="21">
        <name>Other</name>
        <desc>Any other function that cannot be included in an existing domain. The content of this domain will be periodically examined for potential patterns that may give rise to new domains.</desc>
    </domain>
</domains>
